### ISSUE TITLE
Playful language in resume itself

### ISSUE THREAD

**Issue by helenvholmes** [carolinebholmes/resume#1]
I think that the stuff in your ```README``` file is absolutely hilarious. I wonder if it would be worth adding that sort of language in your actual resume? Might mean you would have to handle two versions depending on where you were applying, which could get annoying :confused:

**Comment by carolinebholmes** [comment]
Might consider it if I ever do a website resume, but otherwise I do not feel I have enough developer clout yet to get away with being playful on my actual resume. Maybe after I graduate.
